Replace DG Layers with swisstopo Layer
geometalab/cf_audit pull request #1
Opened 2022-12-06 09:53 UTC by nighty34

Request from @sfkeller

2022-12-06 12:07 UTC, das-g commented on www/static/audit.js
> +    'swisstopo SWISSIMAGE': L.tileLayer("https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.swissimage/default/current/3857/{z}/{x}/{y}.jpeg", {maxZoom: 22
Braucht's da nicht auch eine `attribution`?

2022-12-06 12:36 UTC, nighty34 commented on www/static/audit.js
> +    'swisstopo SWISSIMAGE': L.tileLayer("https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.swissimage/default/current/3857/{z}/{x}/{y}.jpeg", {maxZoom: 22
Habe ich nun noch nachgeführt.

2022-12-06 12:42 UTC, das-g requested changes

2022-12-06 12:42 UTC, das-g commented on www/static/audit.js
> +      attribution: '<p>Federal Office of Topography swisstopo</p>' ,maxZoom: 22
```suggestion
      attribution: '<p>Federal Office of Topography swisstopo</p>', maxZoom: 22
```

2022-12-06 12:42 UTC, das-g commented on www/static/audit.js
> +      attribution: '<p>Federal Office of Topography swisstopo</p>' ,maxZoom: 22
Braucht's die `<p>…</p>`-Tags? Bei den anderen Layern werden die Links ja auch einfach ohne Absatz angegeben.

2022-12-08 15:33 UTC, hixi commented on www/static/audit.js
> +      attribution: '<p>Federal Office of Topography swisstopo</p>' ,maxZoom: 22
Die anderen haben jedoch einen <a> Tag. Wenn ich mich nicht irre, macht es Sinn (sieht nicht gut aus), wenn das "nur" text ist ohne einen Tag. Eventuell könnte man einen <span> ausprobieren, aber soviel besser ist das auch nicht.

2022-12-09 09:34 UTC, merged